name: Compare AWS Secrets

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  compare-secrets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Default region for AWS CLI

      # Step 2: Fetch secret names from both regions
      - name: Fetch secret names from both regions
        id: fetch_secret_names
        run: |
          set -e

          REGION1="us-east-1"
          REGION2="us-west-2"

          # Fetch all secret names from both regions
          SECRET_NAMES_1=$(aws secretsmanager list-secrets --region "$REGION1" --query 'SecretList[].Name' --output text)
          SECRET_NAMES_2=$(aws secretsmanager list-secrets --region "$REGION2" --query 'SecretList[].Name' --output text)

          # Save secret names as environment variables
          echo "SECRET_NAMES_1=$SECRET_NAMES_1" >> $GITHUB_ENV
          echo "SECRET_NAMES_2=$SECRET_NAMES_2" >> $GITHUB_ENV

      # Step 3: Fetch and compare all secrets from both regions
      - name: Fetch and compare all secrets
        id: compare_all_secrets
        run: |
          set -e

          # Compare secret names in both regions
          SECRET_NAMES_1=(${{ env.SECRET_NAMES_1 }})
          SECRET_NAMES_2=(${{ env.SECRET_NAMES_2 }})

          # Initialize variables to store mismatches
          MISMATCHES="{}"
          
          # Iterate over secrets in region 1 and compare with region 2
          for SECRET_NAME in "${SECRET_NAMES_1[@]}"; do
            SECRET1=$(aws secretsmanager get-secret-value --region "$REGION1" --secret-id "$SECRET_NAME" --query 'SecretString' --output text || echo "{}")
            SECRET2=$(aws secretsmanager get-secret-value --region "$REGION2" --secret-id "$SECRET_NAME" --query 'SecretString' --output text || echo "{}")

            # Sort secrets and compare
            SORTED_SECRET1=$(echo "$SECRET1" | jq -S .)
            SORTED_SECRET2=$(echo "$SECRET2" | jq -S .)

            if [[ "$SORTED_SECRET1" != "$SORTED_SECRET2" ]]; then
              # Identify mismatches
              REGION1_ONLY=$(echo "$SORTED_SECRET1" | jq -c --argjson secret2 "$SORTED_SECRET2" \
                'to_entries | map(select(.value != ($secret2[.key]))) | from_entries')
              
              REGION2_ONLY=$(echo "$SORTED_SECRET2" | jq -c --argjson secret1 "$SORTED_SECRET1" \
                'to_entries | map(select(.value != ($secret1[.key]))) | from_entries')

              # Merge mismatches into a single JSON
              MISMATCHES=$(jq -n --argjson region1_only "$REGION1_ONLY" --argjson region2_only "$REGION2_ONLY" \
                '{region1_only: $region1_only, region2_only: $region2_only}')
            fi
          done

          # Save mismatches to a file
          echo "$MISMATCHES" > mismatches.json
          MISMATCHES_STRING=$(echo "$MISMATCHES" | jq -c .)
          echo "mismatches=$MISMATCHES_STRING" >> $GITHUB_ENV

      # Step 4: Notify Slack - Secrets Match
      - name: Notify Slack - Secrets Match
        if: env.mismatches == '{}'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Secrets in both regions are identical."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      # Step 5: Notify Slack - Secrets Mismatched
      - name: Notify Slack - Secrets Mismatched
        if: env.mismatches != '{}'
        run: |
          echo "Mismatches file: mismatches.json" # Debug output for mismatches

          # Read mismatches into a string
          MISMATCHES_STRING=$(cat mismatches.json)

          # Extract the mismatched environment variables (only the keys that differ)
          REGION1_ONLY_KEYS=$(echo "$MISMATCHES_STRING" | jq -r '.region1_only | to_entries | map("\(.key): \(.value)") | .[]')
          REGION2_ONLY_KEYS=$(echo "$MISMATCHES_STRING" | jq -r '.region2_only | to_entries | map("\(.key): \(.value)") | .[]')

          # Notify Slack with mismatches as an attachment
          curl -X POST -H 'Content-type: application/json' \
          --data "{
              \"text\": \"⚠️ Secrets in both regions do not match.\",
              \"attachments\": [
                  {
                      \"text\": \"Mismatches in region 1: \n${REGION1_ONLY_KEYS}\nMismatches in region 2: \n${REGION2_ONLY_KEYS}\"
                  }
              ]
          }" ${{ secrets.SLACK_WEBHOOK_URL }}
