name: Compare AWS Secrets

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  compare-secrets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Default region for AWS CLI

      # Step 2: Fetch secrets from both regions (for example purposes, modify this according to your needs)
      - name: Fetch secrets from both regions
        id: fetch_secrets
        run: |
          set -e

          # Fetch secrets from AWS (Modify as per your region and secret names)
          SECRET1=$(aws secretsmanager get-secret-value --secret-id secret1 --query SecretString --output text)
          SECRET2=$(aws secretsmanager get-secret-value --secret-id secret2 --query SecretString --output text)

          # Sort and format secrets using jq
          SORTED_SECRET1=$(echo "$SECRET1" | jq -S .)
          SORTED_SECRET2=$(echo "$SECRET2" | jq -S .)

          # Compare sorted JSON strings
          if [[ "$SORTED_SECRET1" == "$SORTED_SECRET2" ]]; then
              echo "match=true" >> $GITHUB_ENV
          else
              echo "match=false" >> $GITHUB_ENV

              # Identify mismatches using JSON comparison
              REGION1_ONLY=$(echo "$SORTED_SECRET1" | jq -c --argjson secret2 "$SORTED_SECRET2" \
                'to_entries | map(select(.value != ($secret2[.key]))) | from_entries')
              
              REGION2_ONLY=$(echo "$SORTED_SECRET2" | jq -c --argjson secret1 "$SORTED_SECRET1" \
                'to_entries | map(select(.value != ($secret1[.key]))) | from_entries')

              # Combine mismatches
              MISMATCHES=$(jq -n --argjson region1_only "$REGION1_ONLY" --argjson region2_only "$REGION2_ONLY" \
                '{region1_only: $region1_only, region2_only: $region2_only}')

              echo "mismatches=$MISMATCHES" >> $GITHUB_ENV
          fi

      # Step 3: Notify Slack - Secrets Match
      - name: Notify Slack - Secrets Match
        if: env.match == 'true'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Secrets in both regions are identical."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      # Step 4: Notify Slack - Secrets Mismatched
      - name: Notify Slack - Secrets Mismatched
        if: env.match == 'false'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "$(jq -n --arg text "⚠️ Secrets in both regions do not match." \
          --arg mismatches "$MISMATCHES" \
          '{text: $text, details: $mismatches}')" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
