on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  compare-secrets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install jq (optional if you're not using JSON)
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Step 2: Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Default region for AWS CLI

      # Step 3: Fetch secrets from both regions
      - name: Fetch secrets from both regions
        id: fetch_secrets
        run: |
          set -e

          # Define regions and secret name
          REGION1="us-east-1"
          REGION2="us-west-2"
          SECRET_NAME="prod"

          # Fetch secrets from both regions as plain text
          SECRET1=$(aws secretsmanager get-secret-value --region "$REGION1" --secret-id "$SECRET_NAME" --query 'SecretString' --output text || echo "")
          SECRET2=$(aws secretsmanager get-secret-value --region "$REGION2" --secret-id "$SECRET_NAME" --query 'SecretString' --output text || echo "")

          # Clean secrets if they are in JSON format (using jq to parse)
          SECRET1_CLEAN=$(echo "$SECRET1" | jq -r tostring || echo "$SECRET1")
          SECRET2_CLEAN=$(echo "$SECRET2" | jq -r tostring || echo "$SECRET2")

          # Log the cleaned secrets for debugging
          echo "SECRET1_CLEAN: $SECRET1_CLEAN"
          echo "SECRET2_CLEAN: $SECRET2_CLEAN"

          # Trim leading/trailing whitespace and newlines from secrets
          SECRET1_CLEAN=$(echo "$SECRET1_CLEAN" | xargs)
          SECRET2_CLEAN=$(echo "$SECRET2_CLEAN" | xargs)

          # Save cleaned secrets to environment variables for comparison
          echo "SECRET1=$SECRET1_CLEAN" >> $GITHUB_ENV
          echo "SECRET2=$SECRET2_CLEAN" >> $GITHUB_ENV

      # Step 4: Compare secrets and find differences
      - name: Compare secrets and find differences
        id: compare_secrets
        run: |
          set -e

          # Log the comparison
          echo "Comparing SECRET1 and SECRET2"

          # Ensure the secrets are valid JSON
          SECRET1_JSON=$(echo "$SECRET1_CLEAN" | jq -c . 2>/dev/null || echo "invalid")
          SECRET2_JSON=$(echo "$SECRET2_CLEAN" | jq -c . 2>/dev/null || echo "invalid")

          # Check if they are valid JSON
          if [[ "$SECRET1_JSON" == "invalid" || "$SECRET2_JSON" == "invalid" ]]; then
            echo "One or both secrets are not valid JSON, falling back to string comparison."
            DIFF_KEYS=$(diff <(echo "$SECRET1_CLEAN") <(echo "$SECRET2_CLEAN") || true)
          else
            # Use jq to convert the JSON strings into sorted keys and values for comparison
            DIFF_KEYS=$(diff <(echo "$SECRET1_JSON" | jq -S .) <(echo "$SECRET2_JSON" | jq -S .) || true)
          fi

          # Log the diff result for debugging
          echo "DIFFERENCES: $DIFF_KEYS"

          # Check for differences and set match status
          if [ -z "$DIFF_KEYS" ]; then
            echo "match=true" >> $GITHUB_ENV
          else
            echo "match=false" >> $GITHUB_ENV
            # Save the differences directly
            echo "DIFFERENCES=$DIFF_KEYS" >> $GITHUB_ENV

      # Step 5: Send Slack notification for identical secrets
      - name: Send Slack notification for identical secrets
        if: ${{ env.match == 'true' }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Secrets in both regions are identical."}' ${{ secrets.SLACK_WEBHOOK_URL }}

      # Step 6: Notify of differences in secrets
      - name: Notify of differences in secrets
        if: ${{ env.match == 'false' }}
        run: |
          # Extract the differences
          DIFF_CONTENT="${{ env.DIFFERENCES }}"

          # Log the differences content for debugging
          echo "Raw DIFF_CONTENT: $DIFF_CONTENT"

          # Format the differences into a more readable key-value format
          DIFF_JSON=$(echo "$DIFF_CONTENT" | grep -oP '^\+.*' | sed 's/^+//' | jq -R 'split(": ") | {(. [0]): .[1]}')

          # Create a formatted message for Slack
          SLACK_MESSAGE="⚠️ Secrets in both regions do not match. Here are the differences:\n$DIFF_JSON"

          # Print the formatted differences for debugging
          echo "Formatted Differences: $SLACK_MESSAGE"

          # Send Slack notification with the raw diff differences
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
